# Dependencies
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  syntax_highlighter_opts:
    block:
      line_numbers: true

permalink: pretty

source: '.'
destination: './_site'
encoding: UTF-8
exclude:
  - .git/
  - .github/
  - .idea/
  - src/
  - vendor
  - node_modules/
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - yarn.lock
  - package-lock.json
  - bootstrap/

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc

toc:
  max_level: 3

# Social
title: 'Bootstrap Switzerland'
description: 'Bootstrap Switzerland ist ein Fork von Bootstrap Italia. Das Theme wurde auf Basis des Swiss Design Systems neu gestaltet.'
#authors: 'Dipartimento per la trasformazione digitale'
#authors_url: 'https://innovazione.gov.it'
#authors_agid: "Agenzia per l'Italia Digitale"
#authors_agid_url: 'https://www.agid.gov.it/'
social_card_path: '/docs/assets/img/favicons/social-card.png'
social_logo_path: '/docs/assets/img/favicons/android-chrome-192x192.png'
repo: 'https://github.com/puzzle/bootstrap-switzerland/'
developers: 'https://www.puzzle.ch'

# Versions
current_version:		2.16.0
bootstrap_version: 5.2.3
bootstrap_minor: 5.1

# Analytics
# wai_siteid: 'kjpRNRPp1y'

# CDN links
cdn:
  jquery: '<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" crossorigin="anonymous"></script>'
  popper: '<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js" crossorigin="anonymous"></script>'
  owlcarousel: '<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js" crossorigin="anonymous"></script>'
